// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjihbjeybpltbaxadcns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqaWhiamV5YnBsdGJheGFkY25zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MTczNDMsImV4cCI6MjA1ODM5MzM0M30.SnS2F1qOAIFa0V27rXaiYGFSc8cQiCM73-LgG3vIwQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);